/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CinemaInfo {
      
    export type ActorItemStruct = {itemID: string, uri: string}

    export type ActorItemStructOutput = [itemID: string, uri: string] & {itemID: string, uri: string }
  

    export type CinemaItemStruct = {itemID: string, name: string, uri: string, cinemaAddress: AddressLike}

    export type CinemaItemStructOutput = [itemID: string, name: string, uri: string, cinemaAddress: string] & {itemID: string, name: string, uri: string, cinemaAddress: string }
  

    export type FilmItemStruct = {itemID: string, uri: string, title: string}

    export type FilmItemStructOutput = [itemID: string, uri: string, title: string] & {itemID: string, uri: string, title: string }
  

    export type PlaceItemStruct = {itemID: string, uri: string, cinemaId: string}

    export type PlaceItemStructOutput = [itemID: string, uri: string, cinemaId: string] & {itemID: string, uri: string, cinemaId: string }
  

    export type ScreenItemStruct = {itemID: string, uri: string, placeId: string}

    export type ScreenItemStructOutput = [itemID: string, uri: string, placeId: string] & {itemID: string, uri: string, placeId: string }
  
    }

  export interface CinemaInfoInterface extends Interface {
    getFunction(nameOrSignature: "addActor" | "addCinema" | "addFilm" | "addPlace" | "addScreen" | "getActor" | "getAllActors" | "getAllCinemas" | "getAllFilms" | "getAllPlaces" | "getAllPlacesByCinema" | "getAllScreens" | "getAllScreensByPlace" | "getCinema" | "getFilm" | "getPlace" | "getScreen" | "setMarket" | "totalNumberOfActors" | "totalNumberOfCinemas" | "totalNumberOfFilms" | "totalNumberOfPlaces" | "totalNumberOfScreens" | "updateActorUri" | "updateCinemaUri" | "updateFilmUri" | "updatePlaceUri" | "updateScreenUri"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActorCreated" | "CinemaCreated" | "FilmCreated" | "PlaceCreated" | "ScreenCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'addActor', values: [string, string]): string;
encodeFunctionData(functionFragment: 'addCinema', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'addFilm', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'addPlace', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'addScreen', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'getActor', values: [string]): string;
encodeFunctionData(functionFragment: 'getAllActors', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllCinemas', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllFilms', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllPlaces', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllPlacesByCinema', values: [string]): string;
encodeFunctionData(functionFragment: 'getAllScreens', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllScreensByPlace', values: [string]): string;
encodeFunctionData(functionFragment: 'getCinema', values: [string]): string;
encodeFunctionData(functionFragment: 'getFilm', values: [string]): string;
encodeFunctionData(functionFragment: 'getPlace', values: [string]): string;
encodeFunctionData(functionFragment: 'getScreen', values: [string]): string;
encodeFunctionData(functionFragment: 'setMarket', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalNumberOfActors', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalNumberOfCinemas', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalNumberOfFilms', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalNumberOfPlaces', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalNumberOfScreens', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateActorUri', values: [string, string]): string;
encodeFunctionData(functionFragment: 'updateCinemaUri', values: [string, string]): string;
encodeFunctionData(functionFragment: 'updateFilmUri', values: [string, string]): string;
encodeFunctionData(functionFragment: 'updatePlaceUri', values: [string, string]): string;
encodeFunctionData(functionFragment: 'updateScreenUri', values: [string, string]): string;

    decodeFunctionResult(functionFragment: 'addActor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addCinema', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addFilm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addPlace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addScreen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllActors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCinemas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllFilms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllPlaces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllPlacesByCinema', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllScreens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllScreensByPlace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCinema', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFilm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPlace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getScreen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNumberOfActors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNumberOfCinemas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNumberOfFilms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNumberOfPlaces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNumberOfScreens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateActorUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCinemaUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFilmUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePlaceUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateScreenUri', data: BytesLike): Result;
  }

  
    export namespace ActorCreatedEvent {
      export type InputTuple = [id: BigNumberish, itemID: string, uri: string];
      export type OutputTuple = [id: bigint, itemID: string, uri: string];
      export interface OutputObject {id: bigint, itemID: string, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CinemaCreatedEvent {
      export type InputTuple = [id: BigNumberish, itemID: string, name: string, uri: string];
      export type OutputTuple = [id: bigint, itemID: string, name: string, uri: string];
      export interface OutputObject {id: bigint, itemID: string, name: string, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FilmCreatedEvent {
      export type InputTuple = [id: BigNumberish, itemID: string, title: string, uri: string];
      export type OutputTuple = [id: bigint, itemID: string, title: string, uri: string];
      export interface OutputObject {id: bigint, itemID: string, title: string, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlaceCreatedEvent {
      export type InputTuple = [id: BigNumberish, itemID: string, cinemaID: string, uri: string];
      export type OutputTuple = [id: bigint, itemID: string, cinemaID: string, uri: string];
      export interface OutputObject {id: bigint, itemID: string, cinemaID: string, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScreenCreatedEvent {
      export type InputTuple = [id: BigNumberish, itemID: string, placeID: string, uri: string];
      export type OutputTuple = [id: bigint, itemID: string, placeID: string, uri: string];
      export interface OutputObject {id: bigint, itemID: string, placeID: string, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CinemaInfo extends BaseContract {
    
    connect(runner?: ContractRunner | null): CinemaInfo;
    waitForDeployment(): Promise<this>;

    interface: CinemaInfoInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addActor: TypedContractMethod<
      [actorId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    addCinema: TypedContractMethod<
      [cinemaId: string, name: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    addFilm: TypedContractMethod<
      [filmId: string, title: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    addPlace: TypedContractMethod<
      [placeId: string, cinemaId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    addScreen: TypedContractMethod<
      [screenId: string, placeId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    getActor: TypedContractMethod<
      [actorId: string, ],
      [CinemaInfo.ActorItemStructOutput],
      'view'
    >
    

    
    getAllActors: TypedContractMethod<
      [],
      [CinemaInfo.ActorItemStructOutput[]],
      'view'
    >
    

    
    getAllCinemas: TypedContractMethod<
      [],
      [CinemaInfo.CinemaItemStructOutput[]],
      'view'
    >
    

    
    getAllFilms: TypedContractMethod<
      [],
      [CinemaInfo.FilmItemStructOutput[]],
      'view'
    >
    

    
    getAllPlaces: TypedContractMethod<
      [],
      [CinemaInfo.PlaceItemStructOutput[]],
      'view'
    >
    

    
    getAllPlacesByCinema: TypedContractMethod<
      [cinemaId: string, ],
      [CinemaInfo.PlaceItemStructOutput[]],
      'view'
    >
    

    
    getAllScreens: TypedContractMethod<
      [],
      [CinemaInfo.ScreenItemStructOutput[]],
      'view'
    >
    

    
    getAllScreensByPlace: TypedContractMethod<
      [placeId: string, ],
      [CinemaInfo.ScreenItemStructOutput[]],
      'view'
    >
    

    
    getCinema: TypedContractMethod<
      [cinemaId: string, ],
      [CinemaInfo.CinemaItemStructOutput],
      'view'
    >
    

    
    getFilm: TypedContractMethod<
      [filmId: string, ],
      [CinemaInfo.FilmItemStructOutput],
      'view'
    >
    

    
    getPlace: TypedContractMethod<
      [placeId: string, ],
      [CinemaInfo.PlaceItemStructOutput],
      'view'
    >
    

    
    getScreen: TypedContractMethod<
      [screenId: string, ],
      [CinemaInfo.ScreenItemStructOutput],
      'view'
    >
    

    
    setMarket: TypedContractMethod<
      [market: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalNumberOfActors: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalNumberOfCinemas: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalNumberOfFilms: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalNumberOfPlaces: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalNumberOfScreens: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateActorUri: TypedContractMethod<
      [actorId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateCinemaUri: TypedContractMethod<
      [cinemaId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateFilmUri: TypedContractMethod<
      [filmId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    updatePlaceUri: TypedContractMethod<
      [placeId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateScreenUri: TypedContractMethod<
      [screenId: string, uri: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addActor'): TypedContractMethod<
      [actorId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addCinema'): TypedContractMethod<
      [cinemaId: string, name: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addFilm'): TypedContractMethod<
      [filmId: string, title: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addPlace'): TypedContractMethod<
      [placeId: string, cinemaId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addScreen'): TypedContractMethod<
      [screenId: string, placeId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getActor'): TypedContractMethod<
      [actorId: string, ],
      [CinemaInfo.ActorItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getAllActors'): TypedContractMethod<
      [],
      [CinemaInfo.ActorItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllCinemas'): TypedContractMethod<
      [],
      [CinemaInfo.CinemaItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllFilms'): TypedContractMethod<
      [],
      [CinemaInfo.FilmItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllPlaces'): TypedContractMethod<
      [],
      [CinemaInfo.PlaceItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllPlacesByCinema'): TypedContractMethod<
      [cinemaId: string, ],
      [CinemaInfo.PlaceItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllScreens'): TypedContractMethod<
      [],
      [CinemaInfo.ScreenItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllScreensByPlace'): TypedContractMethod<
      [placeId: string, ],
      [CinemaInfo.ScreenItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCinema'): TypedContractMethod<
      [cinemaId: string, ],
      [CinemaInfo.CinemaItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFilm'): TypedContractMethod<
      [filmId: string, ],
      [CinemaInfo.FilmItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPlace'): TypedContractMethod<
      [placeId: string, ],
      [CinemaInfo.PlaceItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getScreen'): TypedContractMethod<
      [screenId: string, ],
      [CinemaInfo.ScreenItemStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'setMarket'): TypedContractMethod<
      [market: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalNumberOfActors'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalNumberOfCinemas'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalNumberOfFilms'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalNumberOfPlaces'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalNumberOfScreens'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateActorUri'): TypedContractMethod<
      [actorId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCinemaUri'): TypedContractMethod<
      [cinemaId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFilmUri'): TypedContractMethod<
      [filmId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePlaceUri'): TypedContractMethod<
      [placeId: string, uri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateScreenUri'): TypedContractMethod<
      [screenId: string, uri: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ActorCreated'): TypedContractEvent<ActorCreatedEvent.InputTuple, ActorCreatedEvent.OutputTuple, ActorCreatedEvent.OutputObject>;
getEvent(key: 'CinemaCreated'): TypedContractEvent<CinemaCreatedEvent.InputTuple, CinemaCreatedEvent.OutputTuple, CinemaCreatedEvent.OutputObject>;
getEvent(key: 'FilmCreated'): TypedContractEvent<FilmCreatedEvent.InputTuple, FilmCreatedEvent.OutputTuple, FilmCreatedEvent.OutputObject>;
getEvent(key: 'PlaceCreated'): TypedContractEvent<PlaceCreatedEvent.InputTuple, PlaceCreatedEvent.OutputTuple, PlaceCreatedEvent.OutputObject>;
getEvent(key: 'ScreenCreated'): TypedContractEvent<ScreenCreatedEvent.InputTuple, ScreenCreatedEvent.OutputTuple, ScreenCreatedEvent.OutputObject>;

    filters: {
      
      'ActorCreated(uint256,string,string)': TypedContractEvent<ActorCreatedEvent.InputTuple, ActorCreatedEvent.OutputTuple, ActorCreatedEvent.OutputObject>;
      ActorCreated: TypedContractEvent<ActorCreatedEvent.InputTuple, ActorCreatedEvent.OutputTuple, ActorCreatedEvent.OutputObject>;
    

      'CinemaCreated(uint256,string,string,string)': TypedContractEvent<CinemaCreatedEvent.InputTuple, CinemaCreatedEvent.OutputTuple, CinemaCreatedEvent.OutputObject>;
      CinemaCreated: TypedContractEvent<CinemaCreatedEvent.InputTuple, CinemaCreatedEvent.OutputTuple, CinemaCreatedEvent.OutputObject>;
    

      'FilmCreated(uint256,string,string,string)': TypedContractEvent<FilmCreatedEvent.InputTuple, FilmCreatedEvent.OutputTuple, FilmCreatedEvent.OutputObject>;
      FilmCreated: TypedContractEvent<FilmCreatedEvent.InputTuple, FilmCreatedEvent.OutputTuple, FilmCreatedEvent.OutputObject>;
    

      'PlaceCreated(uint256,string,string,string)': TypedContractEvent<PlaceCreatedEvent.InputTuple, PlaceCreatedEvent.OutputTuple, PlaceCreatedEvent.OutputObject>;
      PlaceCreated: TypedContractEvent<PlaceCreatedEvent.InputTuple, PlaceCreatedEvent.OutputTuple, PlaceCreatedEvent.OutputObject>;
    

      'ScreenCreated(uint256,string,string,string)': TypedContractEvent<ScreenCreatedEvent.InputTuple, ScreenCreatedEvent.OutputTuple, ScreenCreatedEvent.OutputObject>;
      ScreenCreated: TypedContractEvent<ScreenCreatedEvent.InputTuple, ScreenCreatedEvent.OutputTuple, ScreenCreatedEvent.OutputObject>;
    
    };
  }