/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CinemaMarket {
      
    export type CinemaItemStruct = {itemID: BigNumberish, name: string, nftContract: AddressLike, owner: AddressLike}

    export type CinemaItemStructOutput = [itemID: bigint, name: string, nftContract: string, owner: string] & {itemID: bigint, name: string, nftContract: string, owner: string }
  

    export type MarketItemStruct = {itemID: BigNumberish, nftContract: AddressLike, tokenID: BigNumberish, seller: AddressLike, owner: AddressLike, price: BigNumberish, sold: boolean}

    export type MarketItemStructOutput = [itemID: bigint, nftContract: string, tokenID: bigint, seller: string, owner: string, price: bigint, sold: boolean] & {itemID: bigint, nftContract: string, tokenID: bigint, seller: string, owner: string, price: bigint, sold: boolean }
  

    export type TicketItemStruct = {itemID: BigNumberish, title: string, nftContract: AddressLike, owner: AddressLike, price: BigNumberish, screenId: string, uri: string}

    export type TicketItemStructOutput = [itemID: bigint, title: string, nftContract: string, owner: string, price: bigint, screenId: string, uri: string] & {itemID: bigint, title: string, nftContract: string, owner: string, price: bigint, screenId: string, uri: string }
  
    }

  export interface CinemaMarketInterface extends Interface {
    getFunction(nameOrSignature: "createCinemaChain" | "createMarketItem" | "createMarketItemFromNFT" | "createMarketSale" | "createTicket" | "fetchCinemaChains" | "fetchMarketItems" | "fetchTicketsByScreenId" | "fetchTicketsForOwner" | "getNumberOfTickets" | "owner" | "setUSDCAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CinemaCreated" | "MarketItemCreated" | "MarketItemSold" | "TicketCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createCinemaChain', values: [string]): string;
encodeFunctionData(functionFragment: 'createMarketItem', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createMarketItemFromNFT', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createMarketSale', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTicket', values: [AddressLike, string, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'fetchCinemaChains', values?: undefined): string;
encodeFunctionData(functionFragment: 'fetchMarketItems', values?: undefined): string;
encodeFunctionData(functionFragment: 'fetchTicketsByScreenId', values: [string]): string;
encodeFunctionData(functionFragment: 'fetchTicketsForOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getNumberOfTickets', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setUSDCAddress', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createCinemaChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarketItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarketItemFromNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarketSale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTicket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchCinemaChains', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchMarketItems', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchTicketsByScreenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fetchTicketsForOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNumberOfTickets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDCAddress', data: BytesLike): Result;
  }

  
    export namespace CinemaCreatedEvent {
      export type InputTuple = [itemID: BigNumberish, name: string, nftContract: AddressLike, owner: AddressLike];
      export type OutputTuple = [itemID: bigint, name: string, nftContract: string, owner: string];
      export interface OutputObject {itemID: bigint, name: string, nftContract: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketItemCreatedEvent {
      export type InputTuple = [itemID: BigNumberish, nftContract: AddressLike, tokenID: BigNumberish, seller: AddressLike, owner: AddressLike, price: BigNumberish, sold: boolean];
      export type OutputTuple = [itemID: bigint, nftContract: string, tokenID: bigint, seller: string, owner: string, price: bigint, sold: boolean];
      export interface OutputObject {itemID: bigint, nftContract: string, tokenID: bigint, seller: string, owner: string, price: bigint, sold: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketItemSoldEvent {
      export type InputTuple = [itemID: BigNumberish, nftContract: AddressLike, tokenID: BigNumberish, newOwner: AddressLike, price: BigNumberish];
      export type OutputTuple = [itemID: bigint, nftContract: string, tokenID: bigint, newOwner: string, price: bigint];
      export interface OutputObject {itemID: bigint, nftContract: string, tokenID: bigint, newOwner: string, price: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TicketCreatedEvent {
      export type InputTuple = [itemID: BigNumberish, title: string, nftContract: AddressLike, owner: AddressLike, price: BigNumberish, ticketURI: string];
      export type OutputTuple = [itemID: bigint, title: string, nftContract: string, owner: string, price: bigint, ticketURI: string];
      export interface OutputObject {itemID: bigint, title: string, nftContract: string, owner: string, price: bigint, ticketURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CinemaMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): CinemaMarket;
    waitForDeployment(): Promise<this>;

    interface: CinemaMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createCinemaChain: TypedContractMethod<
      [tokenName: string, ],
      [string],
      'nonpayable'
    >
    

    
    createMarketItem: TypedContractMethod<
      [nftContract: AddressLike, tokenID: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createMarketItemFromNFT: TypedContractMethod<
      [nftContract: AddressLike, tokenID: BigNumberish, price: BigNumberish, minter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    createMarketSale: TypedContractMethod<
      [nftContract: AddressLike, itemID: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTicket: TypedContractMethod<
      [cinemaAddress: AddressLike, filmName: string, ticketURI: string, price: BigNumberish, screenId: string, ],
      [void],
      'nonpayable'
    >
    

    
    fetchCinemaChains: TypedContractMethod<
      [],
      [CinemaMarket.CinemaItemStructOutput[]],
      'view'
    >
    

    
    fetchMarketItems: TypedContractMethod<
      [],
      [CinemaMarket.MarketItemStructOutput[]],
      'view'
    >
    

    
    fetchTicketsByScreenId: TypedContractMethod<
      [screenId: string, ],
      [CinemaMarket.TicketItemStructOutput[]],
      'view'
    >
    

    
    fetchTicketsForOwner: TypedContractMethod<
      [ticketOwner: AddressLike, ],
      [CinemaMarket.TicketItemStructOutput[]],
      'view'
    >
    

    
    getNumberOfTickets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setUSDCAddress: TypedContractMethod<
      [usdcAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createCinemaChain'): TypedContractMethod<
      [tokenName: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMarketItem'): TypedContractMethod<
      [nftContract: AddressLike, tokenID: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMarketItemFromNFT'): TypedContractMethod<
      [nftContract: AddressLike, tokenID: BigNumberish, price: BigNumberish, minter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMarketSale'): TypedContractMethod<
      [nftContract: AddressLike, itemID: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTicket'): TypedContractMethod<
      [cinemaAddress: AddressLike, filmName: string, ticketURI: string, price: BigNumberish, screenId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fetchCinemaChains'): TypedContractMethod<
      [],
      [CinemaMarket.CinemaItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'fetchMarketItems'): TypedContractMethod<
      [],
      [CinemaMarket.MarketItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'fetchTicketsByScreenId'): TypedContractMethod<
      [screenId: string, ],
      [CinemaMarket.TicketItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'fetchTicketsForOwner'): TypedContractMethod<
      [ticketOwner: AddressLike, ],
      [CinemaMarket.TicketItemStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getNumberOfTickets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setUSDCAddress'): TypedContractMethod<
      [usdcAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CinemaCreated'): TypedContractEvent<CinemaCreatedEvent.InputTuple, CinemaCreatedEvent.OutputTuple, CinemaCreatedEvent.OutputObject>;
getEvent(key: 'MarketItemCreated'): TypedContractEvent<MarketItemCreatedEvent.InputTuple, MarketItemCreatedEvent.OutputTuple, MarketItemCreatedEvent.OutputObject>;
getEvent(key: 'MarketItemSold'): TypedContractEvent<MarketItemSoldEvent.InputTuple, MarketItemSoldEvent.OutputTuple, MarketItemSoldEvent.OutputObject>;
getEvent(key: 'TicketCreated'): TypedContractEvent<TicketCreatedEvent.InputTuple, TicketCreatedEvent.OutputTuple, TicketCreatedEvent.OutputObject>;

    filters: {
      
      'CinemaCreated(uint256,string,address,address)': TypedContractEvent<CinemaCreatedEvent.InputTuple, CinemaCreatedEvent.OutputTuple, CinemaCreatedEvent.OutputObject>;
      CinemaCreated: TypedContractEvent<CinemaCreatedEvent.InputTuple, CinemaCreatedEvent.OutputTuple, CinemaCreatedEvent.OutputObject>;
    

      'MarketItemCreated(uint256,address,uint256,address,address,uint256,bool)': TypedContractEvent<MarketItemCreatedEvent.InputTuple, MarketItemCreatedEvent.OutputTuple, MarketItemCreatedEvent.OutputObject>;
      MarketItemCreated: TypedContractEvent<MarketItemCreatedEvent.InputTuple, MarketItemCreatedEvent.OutputTuple, MarketItemCreatedEvent.OutputObject>;
    

      'MarketItemSold(uint256,address,uint256,address,uint256)': TypedContractEvent<MarketItemSoldEvent.InputTuple, MarketItemSoldEvent.OutputTuple, MarketItemSoldEvent.OutputObject>;
      MarketItemSold: TypedContractEvent<MarketItemSoldEvent.InputTuple, MarketItemSoldEvent.OutputTuple, MarketItemSoldEvent.OutputObject>;
    

      'TicketCreated(uint256,string,address,address,uint256,string)': TypedContractEvent<TicketCreatedEvent.InputTuple, TicketCreatedEvent.OutputTuple, TicketCreatedEvent.OutputObject>;
      TicketCreated: TypedContractEvent<TicketCreatedEvent.InputTuple, TicketCreatedEvent.OutputTuple, TicketCreatedEvent.OutputObject>;
    
    };
  }