/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CinemaInfo', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CinemaInfo__factory>
getContractFactory(name: 'CinemaMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CinemaMarket__factory>
getContractFactory(name: 'CinemaTicket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CinemaTicket__factory>
getContractFactory(name: 'USDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.USDC__factory>
getContractFactory(name: 'Lock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Lock__factory>

  getContractAt(name: 'CinemaInfo', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CinemaInfo>
getContractAt(name: 'CinemaMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CinemaMarket>
getContractAt(name: 'CinemaTicket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CinemaTicket>
getContractAt(name: 'USDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.USDC>
getContractAt(name: 'Lock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Lock>

  deployContract(name: 'CinemaInfo', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CinemaInfo>
deployContract(name: 'CinemaMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CinemaMarket>
deployContract(name: 'CinemaTicket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CinemaTicket>
deployContract(name: 'USDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.USDC>
deployContract(name: 'Lock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Lock>

  deployContract(name: 'CinemaInfo', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CinemaInfo>
deployContract(name: 'CinemaMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CinemaMarket>
deployContract(name: 'CinemaTicket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CinemaTicket>
deployContract(name: 'USDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.USDC>
deployContract(name: 'Lock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Lock>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  